import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import HydrationZustand from "./HydrationZustand";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({children}) => {
  return (
    <html lang="en">
    <body className={inter.className}>
    <HydrationZustand>
      {children}
    </HydrationZustand>
    </body>
    </html>
  );
}

export default RootLayout
